# Generated by Django 3.0.6 on 2020-12-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=255, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
    ]
