# Generated by Django 3.1.4 on 2021-01-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_f_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='valor',
            field=models.TextField(),
        ),
    ]
