# Generated by Django 3.1.4 on 2021-01-03 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cte', '0001_initial'),
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0002_f_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTE_FPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cte.cte')),
                ('F_PAGAMENTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.f_pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ENTREGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBS', models.TextField()),
                ('DATA', models.DateTimeField(auto_now=True)),
                ('CTE_FPag', models.ManyToManyField(to='relatorios.CTE_FPag')),
                ('FUNCIONARIOS', models.ManyToManyField(to='funcionarios.FUNCIONARIOS')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('VEICULO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.veiculos')),
            ],
            options={
                'verbose_name': 'ENTREGA',
                'verbose_name_plural': 'ENTREGAs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
