# Generated by Django 3.0.6 on 2020-11-26 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTREGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBS', models.TextField()),
                ('DATA', models.DateTimeField(auto_now=True)),
                ('CTE', models.TextField()),
                ('AJUDANTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ajudante_funcionario', to='funcionarios.FUNCIONARIOS')),
                ('MOTORISTA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='motorista_funcionario', to='funcionarios.FUNCIONARIOS')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('VEICULOS', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.VEICULOS')),
            ],
            options={
                'verbose_name': 'ENTREGA',
                'verbose_name_plural': 'ENTREGAs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
