# Generated by Django 3.1.4 on 2021-01-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alteracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoFUNCIONARIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUNCAO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.cargos')),
                ('FUNCIONARIO', models.ManyToManyField(to='funcionarios.FUNCIONARIOS')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='ALTERACAO',
            field=models.ManyToManyField(blank=True, null=True, to='relatorios.Alteracoes'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='FUNCIONARIOS',
            field=models.ManyToManyField(to='relatorios.FuncaoFUNCIONARIOS'),
        ),
    ]
