# Generated by Django 3.0.6 on 2020-12-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('parametros', '0002_f_pagamento'),
        ('cte', '0001_initial'),
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='VEICULOS',
            new_name='VEICULO',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='AJUDANTE',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='MOTORISTA',
        ),
        migrations.AddField(
            model_name='entrega',
            name='FUNCIONARIOS',
            field=models.ManyToManyField(to='funcionarios.FUNCIONARIOS'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='F_PAGAMENTO',
            field=models.ManyToManyField(to='parametros.F_PAGAMENTO'),
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='CTE',
        ),
        migrations.AddField(
            model_name='entrega',
            name='CTE',
            field=models.ManyToManyField(to='cte.CTE'),
        ),
    ]
