# Generated by Django 3.1.4 on 2021-01-16 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('relatorios', '0002_auto_20210116_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='ALTERACAO',
            field=models.ManyToManyField(blank=True, to='relatorios.Alteracoes'),
        ),
        migrations.RemoveField(
            model_name='funcaofuncionarios',
            name='FUNCIONARIO',
        ),
        migrations.AddField(
            model_name='funcaofuncionarios',
            name='FUNCIONARIO',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcionarios'),
        ),
    ]
