# Generated by Django 3.1.4 on 2020-12-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_f_pagamento'),
        ('cte', '0001_initial'),
        ('relatorios', '0002_auto_20201209_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='CTE',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='F_PAGAMENTO',
        ),
        migrations.CreateModel(
            name='CTE_FPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cte.cte')),
                ('F_PAGAMENTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.f_pagamento')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='CTE_FPag',
            field=models.ManyToManyField(to='relatorios.CTE_FPag'),
        ),
    ]
