# Generated by Django 3.1.4 on 2021-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_auto_20210116_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='OBS',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
