# Generated by Django 3.1.4 on 2021-05-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20210119_1659'),
        ('relatorios', '0007_ctenotfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctenotfound',
            name='F_PAGAMENTO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.f_pagamento'),
        ),
    ]
