# Generated by Django 4.0 on 2022-01-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_entrega_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='date_closed',
            field=models.DateTimeField(blank=True),
        ),
    ]
