# Generated by Django 4.0 on 2022-03-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('relatorios', '0011_alter_entrega_data_alter_entrega_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='who_close',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wclose', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='USUARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='auth.user'),
        ),
    ]
