# Generated by Django 3.0.6 on 2020-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NR_DACTE', models.CharField(max_length=44, unique=True)),
                ('REMETENTE', models.CharField(max_length=255)),
                ('DESTINATARIO', models.CharField(max_length=255)),
                ('NR_CONTROLE', models.CharField(max_length=10)),
                ('VALOR', models.DecimalField(decimal_places=2, max_digits=11)),
                ('VOLUMES', models.CharField(max_length=10)),
                ('NFE', models.TextField()),
            ],
            options={
                'verbose_name': 'CTE',
                'verbose_name_plural': 'CTEs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
