# Generated by Django 3.2.9 on 2021-12-02 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0002_auto_20210417_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cte',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cte',
            name='date_delivered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
