# Generated by Django 3.2.9 on 2021-12-02 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0003_auto_20211202_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='cte',
            name='date_dispatch',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
