# Generated by Django 3.2.9 on 2021-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0004_cte_date_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='date_dispatch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
