# Generated by Django 3.0.6 on 2020-11-26 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CARGOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARGO', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'CARGOS',
                'verbose_name_plural': 'CARGOSs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VEICULOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFERENCIA', models.CharField(max_length=255)),
                ('MODELO', models.CharField(max_length=20)),
                ('PLACA', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'VEICULOS',
                'verbose_name_plural': 'VEICULOSs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FUNCIONARIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=255)),
                ('SOBRENOME', models.CharField(max_length=255)),
                ('SITUACAO', models.BooleanField(default=1)),
                ('CARGO', models.ManyToManyField(to='funcionarios.CARGOS')),
                ('USUARIO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FUNCIONARIOS',
                'verbose_name_plural': 'FUNCIONARIOSs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
