# Generated by Django 3.1.4 on 2021-06-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_cargos_show_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
