# Generated by Django 3.1.4 on 2021-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_veiculos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
